FROM ubuntu:latest

# UPDATE AND DEPENDENCIES
RUN apt-get update -y
RUN apt-get install curl unzip zip nano git -y

#PYTHON
#RUN apt-get install python-dev -y
RUN apt-get install python3-pip -y

#AWS CLI
RUN pip3 install awscli --upgrade


#ENTRYPOINT
ENTRYPOINT /bin/bash